name: Upload Model to Hugging Face

on: [push]

jobs:
  upload-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install transformers huggingface_hub

    - name: Upload Model to Hugging Face
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        USERNAME: ${{ secrets.USERNAME }}
      run: |
        python help.py
